#.................................................
#   EXIT_PROGRAM.PY, v2.0.0, December 2024, Domenico Lanza.
#.................................................
#   This module is needed to clean the temporary
#   files generated by the program.
#.................................................
import os
from mpp_memory_fixer import delete_mixture_file  # Function to delete the mixture file

def clean_files():
    """This function is used to clean the temporary files.
    """
    # Constants
    MIXTURE_NAME = "temporarily_mixture_file"
    try:
        os.remove("hf_first_comp.var") 
    except:
        pass
    try: 
        os.remove("x.var") 
        os.remove("y.var") 
        os.remove("z.var") 
    except:
        pass
    delete_mixture_file(MIXTURE_NAME)
    return

def exit_program():
    """This function is used to kill the program.
    """
    clean_files()
    print("The program has been killed. Please see the previous errors for more information.")
    exit()

#.................................................
#   Possible improvements:
#   -None
#.................................................
#   KNOW PROBLEMS:
#   None
#.................................................