import mutationpp as mpp
print("START")
mix=mpp.Mixture("nitrogen2")
mix.equilibrate(100,3200)
H=mix.mixtureHMass()
mix.equilibrate(298.15,101325)
print(mix.mixtureHMass())
print(H)
S=mix.mixtureHMinusH0Mass()
print(S)
print(S+H)